# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Serverless.UploadsNotificationLambda

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code
  LambdaUploadsNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dotnet-webapi-UploadsNotificationFunction
      CodeUri: .
      Handler: LambdaSnsSqsNotification
      Runtime: dotnet8
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref UploadsNotificationTopic
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaSQSQueueExecutionRole
        - AmazonSNSFullAccess
      
  LambdaUploadsNotificationFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      FunctionName: !GetAtt LambdaUploadsNotificationFunction.Arn
      EventSourceArn: !GetAtt UploadsNotificationQueue.Arn
      BatchSize: 10
      MaximumBatchingWindowInSeconds: 50

  # Simple Queue Service

  UploadsNotificationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: dotnet-webapi-UploadsNotificationQueue
      Tags:
        - Key: project
          Value: cloudx

  # Simple Notification Service

  UploadsNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "CloudX SNS Upload"
      TopicName: dotnet-webapi-UploadsNotificationTopic
      Tags:
        - Key: project
          Value: cloudx
